# Generated by Django 3.1.2 on 2020-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201006_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='send_to',
            field=models.CharField(max_length=200),
        ),
    ]
